# Generated by Django 4.0 on 2023-06-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_clients_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients_response',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
