# Generated by Django 4.0 on 2023-06-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
